### ISSUE TITLE
FWB link broken in brief.html

### ISSUE THREAD

**Issue by rbmj** [courserules/courserules.github.io#1]
In brief.html you need to s/17/18/ on line 14 - link is broken.

**Comment by tamfr** [comment]
@rbmj Thanks for informing me of this issue.  Can you clarify what "s/17/18" means?  Better yet, if you know of a link that works, send a pull request. Thanks.

**Comment by rbmj** [comment]
Sorry, it's just sed shorthand for "replace 17 with 18"

Didn't think it was worth forking a repo etc to change two bits haha

**Comment by tamfr** [comment]
@rbmj Thanks, updated. Let me know if it works on your end.
